name: Test releases and pull-requests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ 'release/**', 'hotfix/**' ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Number of commits to fetch. 0 indicates all history for all branches and tags. Default: 1

      - name: Setup .NET Core 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Setup GitVersion 5.7.x
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: '5.7.x'

      - name: Execute GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.10

      - name: Print app version
        run: |
          echo "InformationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}"
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Debug --no-restore

      - name: Test
        run: dotnet test --configuration Debug --no-build --verbosity normal

      - name: Create nuget package
        run: dotnet pack -c release -p:packageversion=${{ steps.gitversion.outputs.semVer }} -p:version=${{ steps.gitversion.outputs.semVer }} -p:fileversion=${{ steps.gitversion.outputs.semVer }} -p:informationalversion=${{ steps.gitversion.outputs.informationalVersion }}

      - name: Add GitHub registry nuget source
        run: dotnet nuget add source --username lfsmgs@gmail.com --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Lukkian/index.json"

      - name: Push package to GitHub registry
        run: dotnet nuget push "TypeMember/bin/Release/TypeMember.${{ steps.gitversion.outputs.semVer }}.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
